### ISSUE TITLE
accelerate-llvm-ptx-1.1.0.0 | ghc-8.0.2-a | win10 | Internal error

### ISSUE THREAD

**Issue by oRole** [AccelerateHS/accelerate#400]
Hi Guys, 

currently I'm working on a program for edge detection which I wanted to run on the GPU. I'm using GHC 8.02a, Windows 10 with MSYS/Mingw64-bit and LLVM-5.0.0. While installing accelerate-llvm-ptx-1.1.0.0 the following error appears: 

```
 Data\Array\Accelerate\LLVM\PTX\Compile\Libdevice\Load.hs:106:23: error:
    * Exception when trying to run compile-time code:

*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
.\Data\Array\Accelerate\LLVM\PTX\Compile\Libdevice\TH.hs:109:17: (libdevice): not found: libdevice.compute_35.YY.bc
CallStack (from HasCallStack):
  error, called at .\Data\Array\Accelerate\LLVM\PTX\Compile\Libdevice\TH.hs:109:17 in accelerate-llvm-ptx-1.1.0.0-4Mq9TwHELDpFo5cl6B6FI9:Data.Array.Accelerate.LLVM.PTX.Compile.Libdevice.TH
      Code: libdeviceBitcode (Foreign.CUDA.Analysis.Device.$WCompute 3 5)
    * In the Template Haskell splice $$(libdeviceBitcode (Compute 3 5))
      In the expression: $$(libdeviceBitcode (Compute 3 5))
      In an equation for `libdevice_35_bc':
          libdevice_35_bc = $$(libdeviceBitcode (Compute 3 5))
ghc.exe: addLibrarySearchPath: D:\Programme\CUDA\nvvm\x64 (Win32 error 2): Das System kann die angegebene Datei nicht finden.
cabal: Leaving directory 'C:\Users\Roland\AppData\Local\Temp\cabal-tmp-13852\accelerate-llvm-ptx-1.1.0.0'
cabal: Error: some packages failed to install:
accelerate-llvm-ptx-1.1.0.0 failed during the building phase. The exception
was:
ExitFailure 1
```

Also there is a little error message that a given file could not be found (ghc.exe: addLibrarySearchPath: D:\Programme\CUDA\nvvm\x64 (Win32 error 2)).  Do you know what I'm doing wrong? Any help appreciated.

**Comment by tmcdonell** [comment]
Sorry, i did not see this until now (usually github sends me an email, but not this time..?)

Are you using CUDA-9? I recently recently discovered they changed some internals, and haven't had a chance to update for that yet.

**Comment by oRole** [comment]
No problem! I have to thank for your quick reply. Probably Github doesn't like newbies like me very much. :-)

Yep, I'm using the latest version of CUDA (v9), probably I should have tried an older version, but I ended up using an older version of GHC that runs accelerate-cuda. I kept the other setup, so if it helps you, I of course can test any changes that you made or probably will make.

**Comment by tmcdonell** [comment]
I've made some updates so HEAD should build with CUDA-9 now. I you get a chance to try it out (no rush) let me know how it goes (:

**Comment by oRole** [comment]
Did you upload the changes you mentioned to Hackage? Because there it says the latest update was in October. :)

**Comment by tmcdonell** [comment]
I haven't uploaded to Hackage yet, still testing...

**Comment by tmcdonell** [comment]
I forgot to mention that I have uploaded [cuda-0.9.0.0](http://hackage.haskell.org/package/cuda-0.9.0.0) to Hackage, which should fix this problem. Let me know if that works for you...

**Comment by VorpalChoices** [comment]
I'm getting the same error when compiling accelerate-llvm-ptx-1.1.0.0 on macOS using cuda-0.9.0.0:

```
/private/var/folders/1_/7lhn64251mlg8k4ym2xgkbnr0000gn/T/stack3183/accelerate-llvm-ptx-1.1.0.0/Data/Array/Accelerate/LLVM/PTX/Compile/Libdevice/Load.hs:106:23: error:
    • Exception when trying to run compile-time code:

*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
/private/var/folders/1_/7lhn64251mlg8k4ym2xgkbnr0000gn/T/stack3183/accelerate-llvm-ptx-1.1.0.0/Data/Array/Accelerate/LLVM/PTX/Compile/Libdevice/TH.hs:109:17: (libdevice): not found: libdevice.compute_35.YY.bc
CallStack (from HasCallStack):
    error, called at ./Data/Array/Accelerate/LLVM/PTX/Compile/Libdevice/TH.hs:109:17 in accelerate-llvm-ptx-1.1.0.0-IizoGhsPZ5W9e6CpeOq3vf:Data.Array.Accelerate.LLVM.PTX.Compile.Libdevice.TH
        Code: libdeviceBitcode (Compute 3 5)
    • In the Template Haskell splice $$(libdeviceBitcode (Compute 3 5))
        In the expression: $$(libdeviceBitcode (Compute 3 5))
        In an equation for ‘libdevice_35_bc’:
            libdevice_35_bc = $$(libdeviceBitcode (Compute 3 5))
    |
106 | libdevice_35_bc = $$( libdeviceBitcode (Compute 3 5) )
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Looking at my CUDA-9.0 installation, the only library in `/usr/local/cuda/nvvm/libdevice` is `libdevice.10.bc`. I tried symlinking `libdevice.compute_35.10.bc` (and 20/30/50) to this existing library, which allowed accelerate-llvm-ptx-1.1.0.0 to compile…

…but my program fails to launch with "`dyld: Library not loaded: @rpath/libnvvm.3.2.0.dylib`" (despite setting the environment variables described at http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html). `libnvvm.3.2.0.dylib` is located in `/usr/local/cuda/nvvm/lib`, so I added that to `DYLD_LIBRARY_PATH` and the program launches…

…but when I used `GPU.runN` the program crashes with `ExitFailure (-11)` after the array-fusion phase. Here, I gave up. Any ideas?

**Comment by tmcdonell** [comment]
Hi @VorpalChoices. This should be fixed in HEAD. I'll try and find time to back port the necessary changes to make a patch release.

**Comment by VorpalChoices** [comment]
Hi Trevor,

Thanks for your help. I managed to get it working with a bit of messing around. I'll describe it here for anyone else having the same issues. I put the following in my stack.yaml using the current latest commits:
```
resolver: nightly-2017-12-01
packages:
- .
- location: ../../code/haskell/vendor/accelerate-llvm-bd1c8a5/accelerate-llvm-ptx
  extra-dep: true
- location: ../../code/haskell/vendor/accelerate-llvm-bd1c8a5/accelerate-llvm-native
  extra-dep: true
- location: ../../code/haskell/vendor/accelerate-llvm-bd1c8a5/accelerate-llvm
  extra-dep: true
- location: ../../code/haskell/vendor/accelerate-40adadd
  extra-dep: true
```

This solves the first problem from above, the missing `compute_XX` libraries. The second is still present — I have to add the path for libnvvm to my `DYLD_LIBRARY_PATH`. I'm not sure whether the Nvidia documentation is wrong on this setting? (Note that I'm *not* setting the `nvvm` flag for accelerate-llvm-ptx).

As for the third — my program still crashed. I reverified my CUDA installation, and it turned out not to be working, with error message `-> CUDA driver version is insufficient for CUDA runtime version`. I found a [thread](https://devtalk.nvidia.com/default/topic/1025945/mac-cuda-9-0-driver-fully-compatible-with-macos-high-sierra-10-13-error-quot-update-required-quot-solved-/) on the Nvida forums which suggested that new Nvidia drivers need to be installed after each (even minor) macOS update — and now everything works. Thanks!

---

FYI I'm seeing a problem with the `debug` setting on HEAD. It [looks](https://github.com/haskell/cabal/issues/4306) like Cabal doesn't recompile c-sources in response to cc-options changes, so if you start by compiling with `debug: false`, the `#if defined(ACCELERATE_DEBUG)` in `clock.c` excludes the whole file — which then never gets recompiled, even with `debug: true`, giving linker errors for `clock_gettime_monotonic_seconds` and `clock_gettime_elapsed_seconds`. The fix is to move the conditionality into the cabal file. If that makes sense to you I can submit a pull request.

**Comment by tmcdonell** [comment]
I have run into this cabal issue as well. I just opened a ticket for it here: https://github.com/haskell/cabal/issues/4937.

That is an interesting idea to work around the problem though. Let's see if the Cabal authors respond with any suggestions first... I'm not super keen on duplicating the .c files with minor changes depending on whether we are debug or release mode (rather than having those changes inline with #ifdef`s)

**Comment by JonathanFraser** [comment]
What's the timeline for a point release look like? It seems a lot of systems are stabilising cuda-9 which means a failure to install on any updated system.

**Comment by tmcdonell** [comment]
@JonathanFraser oh, sorry, I totally forgot about that. I should have time that this today/tomorrow.

Always feel free to remind me about stuff like this.

**Comment by tmcdonell** [comment]
Uploaded [accelerate-llvm-ptx-1.1.0.1](https://hackage.haskell.org/package/accelerate-llvm-ptx-1.1.0.1). This should appear in the next lts-10.x series.
